services:
  app:
    build: .
    image: "date-time-app"
    container_name: "date-time-app"
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    working_dir: /rails
    volumes:
      - .:/rails
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

  mysql:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=MysqlRootPassword
      - MARIADB_DATABASE=myappdb
      - MARIADB_USER=myapp
      - MARIADB_PASSWORD=MysqlRootPassword
      - MARIADB_MYSQL_LOCALHOST_USER=1   
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
      - default
      