apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: NodePort
  selector:
    app: rails-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
